import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */

plugins {
    java
    id("io.freefair.lombok") version "4.1.6"
    kotlin("jvm") version "1.3.70"
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(group = "org.forgerock.cuppa", name = "cuppa", version = "1.4.0")
    testImplementation(group = "org.forgerock.cuppa", name = "cuppa-junit", version = "1.4.0")
    testImplementation(group = "junit", name = "junit", version = "4.12")

    testImplementation(group = "org.assertj", name = "assertj-core", version = "3.15.0")

    implementation(group = "org.slf4j", name = "slf4j-log4j12", version = "1.7.25")
    implementation(group = "log4j", name = "log4j", version = "1.2.17")

    implementation(kotlin("stdlib"))
    implementation("io.kubernetes:client-java:6.0.1")
}

tasks {
    test {
        useJUnit()
//        useJUnitPlatform()
    }
    configure<JavaPluginConvention> {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    compileKotlin {
        kotlinOptions {
            jvmTarget = "11"
            languageVersion = "1.3"
            apiVersion = "1.3"
        }
    }
}
